import React, { useState, useEffect } from "react";
import MovieList from "../components/MovieList";

// Dữ liệu phim tĩnh
const moviesData = [
  {
    id: 1,
    title: "Movie 1",
    genre: "action",
    releaseDate: "2023",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 2,
    title: "Movie 2",
    genre: "action",
    releaseDate: "2022",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 3,
    title: "Movie 3",
    genre: "action",
    releaseDate: "2021",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 4,
    title: "Movie 4",
    genre: "action",
    releaseDate: "2020",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 5,
    title: "Movie 1",
    genre: "action",
    releaseDate: "2023",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 6,
    title: "Movie 2",
    genre: "action",
    releaseDate: "2022",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 7,
    title: "Movie 3",
    genre: "action",
    releaseDate: "2021",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 8,
    title: "Movie 4",
    genre: "action",
    releaseDate: "2020",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 9,
    title: "Movie 1",
    genre: "action",
    releaseDate: "2023",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 10,
    title: "Movie 2",
    genre: "action",
    releaseDate: "2022",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 11,
    title: "Movie 3",
    genre: "action",
    releaseDate: "2021",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 12,
    title: "Movie 4",
    genre: "action",
    releaseDate: "2020",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 13,
    title: "Movie 1",
    genre: "action",
    releaseDate: "2023",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 14,
    title: "Movie 2",
    genre: "action",
    releaseDate: "2022",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 15,
    title: "Movie 3",
    genre: "action",
    releaseDate: "2021",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 16,
    title: "Movie 4",
    genre: "action",
    releaseDate: "2020",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 17,
    title: "Movie 1",
    genre: "action",
    releaseDate: "2023",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 18,
    title: "Movie 2",
    genre: "action",
    releaseDate: "2022",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 19,
    title: "Movie 3",
    genre: "action",
    releaseDate: "2021",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 20,
    title: "Movie 4",
    genre: "action",
    releaseDate: "2020",
    description: "Action-packed adventure!",
    image: "/images/actions/movies1.webp",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
];

const ActionPage = () => {
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    // Lọc các phim có genre là "action"
    setMovies(moviesData.filter((movie) => movie.genre === "action"));
  }, []);

  return (
    <div className="movie-list-page">
      <h1>Action Movies</h1>
      <MovieList movies={movies} />
    </div>
  );
};

export default ActionPage;
