// src/pages/AnimationPage.js
import React, { useState, useEffect } from "react";
import MovieList from "../components/MovieList";

const moviesData = [
  {
    id:41,
    title: "Masha and the Bear",
    genre: "animation",
    releaseDate: "2023",
    description: "Masha and the Bear are heroes of Russian folklore, known to all Russian children. Just that in the series they are different and live in the modern world, which gave the creators from Animaccord Animation Studio the ability to bring new possibilities to their interactions. Series tell us about a unique relationship between two main characters. Masha is an exceedingly active little girl who can't sit still on one place and has to make everything a business of her own. The Bear is a big and hearty guy who loves comfort and quietness. After their first met the Bear is always in anticipation for another fun and wild adventure that Masha will surely pull him in.",
    image: "/images/animation/masha1.webp",
    videoUrl: "https://www.youtube.com/embed/_jNnVDz7uE0?si=TBE95ICLG6mYFR1J",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 42,
    title: "Masha and the Bear",
    genre: "animation",
    releaseDate: "2022",
    description: "Masha and the Bear are heroes of Russian folklore, known to all Russian children. Just that in the series they are different and live in the modern world, which gave the creators from Animaccord Animation Studio the ability to bring new possibilities to their interactions. Series tell us about a unique relationship between two main characters. Masha is an exceedingly active little girl who can't sit still on one place and has to make everything a business of her own. The Bear is a big and hearty guy who loves comfort and quietness. After their first met the Bear is always in anticipation for another fun and wild adventure that Masha will surely pull him in.",
    image: "/images/animation/masha2.webp",
    videoUrl: "https://www.youtube.com/embed/nvos59jFxus?si=_zqf5rwBvVZaomsb",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 43,
    title: "Masha and the Bear",
    genre: "animation",
    releaseDate: "2021",
    description: "Masha and the Bear are heroes of Russian folklore, known to all Russian children. Just that in the series they are different and live in the modern world, which gave the creators from Animaccord Animation Studio the ability to bring new possibilities to their interactions. Series tell us about a unique relationship between two main characters. Masha is an exceedingly active little girl who can't sit still on one place and has to make everything a business of her own. The Bear is a big and hearty guy who loves comfort and quietness. After their first met the Bear is always in anticipation for another fun and wild adventure that Masha will surely pull him in.",
    image: "/images/animation/masha3.jpeg",
    videoUrl: "https://www.youtube.com/embed/eOfw501ADzA?si=Amd218xa1yxBzlpg",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 44,
    title: "Masha and the Bear",
    genre: "animation",
    releaseDate: "2020",
    description: "Masha and the Bear are heroes of Russian folklore, known to all Russian children. Just that in the series they are different and live in the modern world, which gave the creators from Animaccord Animation Studio the ability to bring new possibilities to their interactions. Series tell us about a unique relationship between two main characters. Masha is an exceedingly active little girl who can't sit still on one place and has to make everything a business of her own. The Bear is a big and hearty guy who loves comfort and quietness. After their first met the Bear is always in anticipation for another fun and wild adventure that Masha will surely pull him in.",
    image: "/images/animation/masha4.jpg",
    videoUrl: "https://www.youtube.com/embed/gw2EYWXniZI?si=3KQaaxnEt5ZxOVlH",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 45,
    title: "Bản giao hưởng địa cầu",
    genre: "animation",
    releaseDate: "2023",
    description: "Chuẩn bị cho buổi hòa nhạc ở trường, Nobita đang tập thổi sáo recorder - nhạc cụ mà cậu dở tệ nhất. Thích thú trước nốt No lạc quẻ của Nobita , Micca - cô bé bí ẩn đã mời Doraemon , Nobita cùng nhóm bạn đến Farre - Cung điện âm nhạc tọa lạc trên một hành tinh nơi âm nhạc sẽ hóa thành năng lượng. Nhằm cứu cung điện này, Micca và Chapeck đang tìm kiếm 5 Virtouso - bậc thầy âm nhạc huyền thoại sẽ cùng mình biểu diễn! Với bảo bối thần kì Chứng chỉ chuyên viên âm nhạc, Doraemon và các bạn đã chọn nhạc bằng sợi dây thần định mệnh, cùng Micca hòa tấu, từng bước khôi phục cung điện Farre. Tuy nhiên, một vật thể sống đáng sợ rất ghét âm nhạc sẽ xóa sổ âm nhạc khỏi thế giới đang đến gần, Trái Đất đang rơi vào nguy hiểm",
    image: "/images/animation/mon1.jpg",
    videoUrl: "https://www.youtube.com/embed/T88JbV6jwfE?si=68XcvFzRAkaDJgqL",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 46,
    title: "Nobita và vùng đất lý tưởng trên bầu trời",
    genre: "animation",
    releaseDate: "2022",
    description: "Với kịch bản hoàn toàn mới, đến từ bộ đôi đạo diễn - biên kịch lần đầu tiên thực hiện một phần phim Doraemon, Doraemon: Nobita Và Vùng Đất Lý Tưởng Trên Bầu Trời mang tới một thế giới hoàn toàn mới, với một vùng đất bí ẩn cùng những món bảo bối độc lạ lần đầu xuất hiện.",
    image: "/images/animation/mon2.jpg",
    videoUrl: "https://www.youtube.com/embed/E-hm-KkrbyE?si=CH0U30NWA0DaWcoo",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 47,
    title: "Nobita và chuyến thám hiểm Nam Cực Kachi Kochi",
    genre: "animation",
    releaseDate: "2021",
    description: "âu chuyện kể về chuyến phiêu lưu của nhóm bạn ở một trăm ngàn năm trước tại Nam Cực để giúp những người bạn từ hành tinh Hyoga Hyoga tiêu diệt Blizzaga - kẻ đã đóng băng hành tinh của họ. Chủ đề chính là Tình bạn này",
    image: "/images/animation/mon3.jpg",
    videoUrl: "https://www.youtube.com/embed/uwKWG62kczc?si=IxJwKfoWJuiPTFcY",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 48,
    title: "Nobita & Những Bạn Khủng Long Mới",
    genre: "animation",
    releaseDate: "2020",
    description: "Tình cờ tìm được một quả trứng khủng long hóa thạch, Nobita đã dùng bảo bối “Khăn trùm thời gian” đưa quả trứng trở về thời điểm 100 triệu năm trước và ấp cho trứng nở. Nỗ lực của cậu đã thành công khi loài bò sát thuộc chi Futabasaurus chào đời, được Nobita đặt tên là Pīsuke. Nobita và Doraemon bí mật chăm sóc Pīsuke đến khi trưởng thành, tình bạn giữa cậu và khủng long cũng được vun đắp theo thời gian. Đến khi Pīsuke không thể sống vừa trong nhà nữa, Nobita nuôi khủng long ở hồ nước trong công viên, không may cư dân thành phố phát hiện ra và tiến hành khảo cứu; Nobita và Doraemon buộc phải thả Pīsuke về lại quê hương ở thời kỳ Creta muộn 100 triệu năm trước",
    image: "/images/animation/mon4.png",
    videoUrl: "https://www.youtube.com/embed/LFFaYJwKf4I?si=pFPaitQ-7QmHrWIg",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 49,
    title: "Xin chào jadoo-Trở Về Thời Phong Kiến ",
    genre: "animation",
    releaseDate: "2023",
    description: "Lấy bối cảnh một gia đình bình thường vào những năm 1978 đến đầu những năm 1980 ở Hàn Quốc, phim kể về câu chuyện vui vẻ, ấm áp của năm thành viên trong gia đình",
    image: "/images/animation/doo1.jpg",
    videoUrl: "https://www.youtube.com/embed/wIruMvuImj8?si=C4gyP0yYbDIrUExa",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 50,
    title: "Xin chào jadoo-Những câu chuyện cổ tích ",
    genre: "animation",
    releaseDate: "2022",
    description: "Lấy bối cảnh một gia đình bình thường vào những năm 1978 đến đầu những năm 1980 ở Hàn Quốc, phim kể về câu chuyện vui vẻ, ấm áp của năm thành viên trong gia đình",
    image: "/images/animation/doo2.jpg",
    videoUrl: "https://www.youtube.com/embed/EyM62JndOow?si=lphNKImap9evRRPP",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 51,
    title: "Pokémon",
    genre: "animation",
    releaseDate: "2021",
    description: "Được sáng tạo bởi Satoshi Tajiri vào đầu năm 1989, Pokémon là những sinh vật sống trong Thế giới Pokémon hư cấu. Các thiết kế cho vô số loài có thể lấy cảm hứng từ bất cứ thứ gì, chẳng hạn như các vật thể vô tri, thực vật, động vật thế giới hoặc các thần thoại.",
    image: "/images/animation/poke1.webp",
    videoUrl: "https://www.youtube.com/embed/h9aaxzWb938?si=PQ-_sAVhhXvE3_0O",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 52,
    title: "Pokémon",
    genre: "animation",
    releaseDate: "2020",
    description: "Được sáng tạo bởi Satoshi Tajiri vào đầu năm 1989, Pokémon là những sinh vật sống trong Thế giới Pokémon hư cấu. Các thiết kế cho vô số loài có thể lấy cảm hứng từ bất cứ thứ gì, chẳng hạn như các vật thể vô tri, thực vật, động vật thế giới hoặc các thần thoại.",
    image: "/images/animation/poke2.jpg",
    videoUrl: "https://www.youtube.com/embed/s4l5UWXpoVs?si=9TaYwimnxj9R3PBm",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 53,
    title: "Pokémon",
    genre: "animation",
    releaseDate: "2023",
    description: "Được sáng tạo bởi Satoshi Tajiri vào đầu năm 1989, Pokémon là những sinh vật sống trong Thế giới Pokémon hư cấu. Các thiết kế cho vô số loài có thể lấy cảm hứng từ bất cứ thứ gì, chẳng hạn như các vật thể vô tri, thực vật, động vật thế giới hoặc các thần thoại.",
    image: "/images/animation/poke3.jpg",
    videoUrl: "https://www.youtube.com/embed/MMtmvJs_w0c?si=SeZde5kU84Ffxo8Y",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 54,
    title: "Pokémon",
    genre: "animation",
    releaseDate: "2022",
    description: "Được sáng tạo bởi Satoshi Tajiri vào đầu năm 1989, Pokémon là những sinh vật sống trong Thế giới Pokémon hư cấu. Các thiết kế cho vô số loài có thể lấy cảm hứng từ bất cứ thứ gì, chẳng hạn như các vật thể vô tri, thực vật, động vật thế giới hoặc các thần thoại.",
    image: "/images/animation/poke5.jpg",
    videoUrl: "https://www.youtube.com/embed/E5aSIwfNwds?si=UPyGmW6kblF6ZEw7",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 55,
    title: "Tom & Jerry ",
    genre: "animation",
    releaseDate: "2021",
    description: "It's that time of year again where you gather around the table with your family and loved ones and feast on some good food! Join Tom, Jerry, and their families as they spend time with each other and eat lots of yummy food.",
    image: "/images/animation/tom1.jpg",
    videoUrl: "https://www.youtube.com/embed/cU0pC6vaDmM?si=EAc_7FdPx_fQI9OK",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 56,
    title: "Tom & Jerry ",
    genre: "animation",
    releaseDate: "2020",
    description: "Did you know that there are only 25 classic Tom & Jerry episodes that were displayed in a widescreen CinemaScope from the 1950s",
    image: "/images/animation/tom2.webp",
    videoUrl: "https://www.youtube.com/embed/t0Q2otsqC4I?si=F1fFrI9BsGBxvdKM",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 57,
    title: "Thám Tử Lừng Danh Conan",
    genre: "animation",
    releaseDate: "2023",
    description: "Thám tử lừng danh Conan xoay quanh câu chuyện về chàng thám tử Kudo Shinichi, trong một lần đang điều tra đã bị Tổ chức Áo Đen ép uống thuốc độc, khiến cho cơ thể bị teo nhỏ. Sau đó, Shinichi chuyển đến sống ở nhà của người bạn thuở niên thiếu Ran Mori cùng người bố Kogoro Mori. Tại đây, cậu dùng văn phòng thám tử của ông Kogoro để truy tìm tung tích của tổ chức Áo Đen đồng thời giúp ông phá nhiều vụ án dưới một thân phận mới là Conan Edogawa.",
    image: "/images/animation/conan1.jpg",
    videoUrl: "https://www.youtube.com/embed/e_E3T-i0LSY?si=2bDtqGdMZfUA08S3",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 58,
    title: "Thám Tử Lừng Danh Conan",
    genre: "animation",
    releaseDate: "2022",
    description: "Thám tử lừng danh Conan xoay quanh câu chuyện về chàng thám tử Kudo Shinichi, trong một lần đang điều tra đã bị Tổ chức Áo Đen ép uống thuốc độc, khiến cho cơ thể bị teo nhỏ. Sau đó, Shinichi chuyển đến sống ở nhà của người bạn thuở niên thiếu Ran Mori cùng người bố Kogoro Mori. Tại đây, cậu dùng văn phòng thám tử của ông Kogoro để truy tìm tung tích của tổ chức Áo Đen đồng thời giúp ông phá nhiều vụ án dưới một thân phận mới là Conan Edogawa.",
    image: "/images/animation/conan2.jpg",
    videoUrl: "https://www.youtube.com/embed/s59MUtFxsZQ?si=jaiR7xPidgJxODaK",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 59,
    title: "Snow White & the Seven Dwarfs",
    genre: "animation",
    releaseDate: "2021",
    description: "Nàng Bạch Tuyết và bảy chú lùn (tiếng Anh: Snow White and the Seven Dwarfs) là phim hoạt hình điện ảnh được sản xuất năm 1937, phim hoạt hình điện ảnh đầu tiên của Walt Disney. Mặc dù không phải phim hoạt hình điện ảnh đầu tiên được sản xuất (phim El Apóstol của Argentina năm 1917 có thể là phim đầu tiên hoặc phim Cuộc phiêu lưu của hoàng tử Achmed năm 1926), Bạch Tuyết và Bảy chú lùn là bộ phim hoạt hình điện ảnh đầu tiên thành công rộng rãi trong cộng đồng nói tiếng Anh và là phim đầu tiên sử dụng âm thanh-trên-phim (Quirino Cristiani sử dụng âm thanh trên đĩa năm 1931). Bạch Tuyết cũng là phim đầu tiên được quay bằng công nghệ Technicolor.",
    image: "/images/animation/snow.jpg",
    videoUrl: "https://www.youtube.com/embed/tRQSwbcJQGI?si=TKM1uvpBDc8MsmGa",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 60,
    title: "Cô Bé Lọ Lem (Cinderella)",
    genre: "animation",
    releaseDate: "2020",
    description: "Ngày xửa ngày xưa, có nàng Lọ Lem sống hạnh phúc bên cha mẹ yêu quý. Nhưng đến một ngày kia mẹ mất, cha Lọ Lem tái giá với bà Tremaine, một người phụ nữ độc ác có hai đứa con gái đáng ghét tên là Drizella và Anastasia. Khi cha qua đời, bà mẹ kế coi nàng như kẻ tôi tớ trong nhà, bắt nàng làm việc quần quật suốt cả ngày. Lọ Lem đành chấp nhận số phận, làm việc chăm chỉ và rất nghe lời dì ghẻ. Cuộc sống cứ thế trôi qua cho đến một ngày kia, nhà vua quyết định đã đến lúc con trai ông phải tìm một người vợ để sinh cho ông những đứa cháu đáng yêu. Vì thế ông mở một buổi dạ hội và mời toàn thể các thiếu nữ chưa chồng tới dự để hoàng tử có thể chọn được cô gái ưng ý nhất. Lọ Lem nghe tin và hỏi mụ dì ghẻ. Mụ dì ghẻ ra điều kiện rằng cô phải làm xong mọi việc và có một bộ váy phù hợp để đi dự tiệc. Trong khi cô làm việc, chuột và chim đã bí mật sửa lại cho Cinderella chiếc váy cũ của mẹ cô. Những con vật lấy dây chuyền và mảnh vải mà hay cô chị vứt đi. Khi xe ngựa đã đến để đón mọi người đi đến bữa tiệc. Cinderella chạy xuống và khoe mọi người về chiếc váy đó. Mụ dì ghẻ bảo rằng nó thật là đẹp với thái độ khó chịu. Còn hai cô chị thì hét lên rằng đó là chiếc vòng cổ của con, đó là váy của con",
    image: "/images/animation/lolem.jpg",
    videoUrl: "https://www.youtube.com/embed/TW0D9g16_MY?si=-dQYQO3t9HeHPUXa",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
];

const AnimationPage = () => {
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    setMovies(moviesData.filter((movie) => movie.genre === "animation"));
  }, []);

  return (
    <div className="movie-list-page">
      <h1>Animation Movies</h1>
      <MovieList movies={movies} />
    </div>
  );
};

export default AnimationPage;
