// src/pages/RomancePage.js
import React, { useState, useEffect } from "react";
import MovieList from "../components/MovieList";

const moviesData = [
  {
    id: 61,
    title: "Trần Thiên Thiên trong lời đồn",
    genre: "romance",
    releaseDate: "2023",
    description: " Câu chuyện tình yêu ngọt ngào giữa Bối Vy Vy, một nữ game thủ xinh đẹp và Tiêu Nại, chàng trai hoàn hảo từ ngoại hình đến tài năng. Họ quen nhau qua một trò chơi trực tuyến và dần xây dựng một mối quan hệ đời thực đầy lãng mạn.",
    image: "/images/romantic/p.jpg",
    videoUrl: "https://www.youtube.com/embed/kx02T-jNUuQ?si=mynHW6pmRC_4kl45",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 62,
    title: "Vụng Trộm Không Thể Giấu",
    genre: "romance",
    releaseDate: "2022",
    description: "Dựa trên tiểu thuyết của Tân Di Ổ, phim kể về hành trình trưởng thành và những câu chuyện tình yêu của Trịnh Vy, một cô gái năng động. Giữa tình cảm với hai người đàn ông khác nhau, cô phải đưa ra những quyết định thay đổi cả cuộc đời mình.",
    image: "/images/romantic/movi44.jpg",
    videoUrl: "https://www.youtube.com/embed/2PPJHjPlr2c?si=REa9yI8SxXvTmU3s",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 63,
    title: "Hello My Girl",
    genre: "romance",
    releaseDate: "2021",
    description: "Phim kể về mối tình đầu khắc cốt ghi tâm giữa Hà Dĩ Thâm, một luật sư điển trai và Triệu Mặc Sênh, một cô gái ngây thơ. Sau nhiều năm xa cách vì hiểu lầm, họ gặp lại và đối mặt với quá khứ để tìm lại tình yêu.",
    image: "/images/romantic/movi4444.jpg",
    videoUrl: "https://www.youtube.com/embed/OHIVWcGUKSE?si=29uIv_aR-kqbAJVZ",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 64,
    title: "Hạ Cánh Nơi Anh",
    genre: "romance",
    releaseDate: "2020",
    description: "Han Thương Ngôn, một tuyển thủ game thể thao điện tử tài năng nhưng lạnh lùng, tình cờ gặp gỡ và bị cuốn vào sự đáng yêu của Đồng Niên, một nữ ca sĩ kiêm lập trình viên thông minh. Câu chuyện xoay quanh tình yêu, ước mơ, và sự nỗ lực trong cuộc sống.",
    image: "/images/romantic/movi44444.jpg",
    videoUrl: "https://www.youtube.com/embed/x8Pliysytls?si=8mkQRdta0TuyvFYb",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 65,
    title: "Tôi Độc Thân dựa vào thực lực",
    genre: "romance",
    releaseDate: "2023",
    description: "Câu chuyện tình yêu đau thương giữa Cẩm Mịch, con gái của Hoa Thần và Húc Phượng, con trai Thiên Đế. Họ trải qua nhiều kiếp nạn, hiểu lầm và thử thách để tìm đến tình yêu đích thực.",
    image: "/images/romantic/movi444444.jpg",
    videoUrl: "https://www.youtube.com/embed/0eM4MUXlGb4?si=OATZP_nz3R08UW8P",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 66,
    title: "hậu duệ mặt trời",
    genre: "romance",
    releaseDate: "2022",
    description: "Dựa trên tiểu thuyết nổi tiếng của Đường Thất Công Tử, phim xoay quanh mối tình ba kiếp giữa Bạch Thiển, thượng thần cao quý của Thanh Khâu, và Dạ Hoa, thái tử Thiên tộc.",
    image: "/images/romantic/movi.jpg",
    videoUrl: "https://www.youtube.com/embed/z7GTGBBbV2w?si=vZWtAGVZ0h5lG5qt",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 67,
    title: "Ngày em đẹp nhất",
    genre: "romance",
    releaseDate: "2016",
    description: "Câu chuyện về Chu Phóng, một nhà thiết kế thời trang tài năng nhưng bướng bỉnh, và Tống Lẫm, một doanh nhân lạnh lùng. Họ ban đầu là đối thủ nhưng dần phát triển tình cảm qua những lần hợp tác.",
    image: "/images/romantic/moivii.jpg",
    videoUrl: "https://www.youtube.com/embed/YvnBsiTidTk?si=0Fmbnzq46AIF-J3o",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 68,
    title: "Lắng nghe giai điệu tình yêu",
    genre: "romance",
    releaseDate: "2020",
    description: " Câu chuyện tình yêu ngọt ngào giữa Bối Vy Vy, một nữ game thủ xinh đẹp và Tiêu Nại, chàng trai hoàn hảo từ ngoại hình đến tài năng. Họ quen nhau qua một trò chơi trực tuyến và dần xây dựng một mối quan hệ đời thực đầy lãng mạn.",
    image: "/images/romantic/moviii.jpg",
    videoUrl: "https://www.youtube.com/embed/m-mEbAQZDlg?si=JVV0Wy01ZXCoyJA3",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 69,
    title: "Thư ký sao thế!",
    genre: "romance",
    releaseDate: "2018",
    description: "Han Thương Ngôn, một tuyển thủ game thể thao điện tử tài năng nhưng lạnh lùng, tình cờ gặp gỡ và bị cuốn vào sự đáng yêu của Đồng Niên, một nữ ca sĩ kiêm lập trình viên thông minh. Câu chuyện xoay quanh tình yêu, ước mơ, và sự nỗ lực trong cuộc sống.",
    image: "/images/romantic/movie.jpg",
    videoUrl: "https://www.youtube.com/embed/7UvJOZQFWwM?si=AaIvh-gQPVmDvGud",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 70,
    title: "Tầng lớp Itaewon",
    genre: "romance",
    releaseDate: "2022",
    description: " Câu chuyện tình yêu ngọt ngào giữa Bối Vy Vy, một nữ game thủ xinh đẹp và Tiêu Nại, chàng trai hoàn hảo từ ngoại hình đến tài năng. Họ quen nhau qua một trò chơi trực tuyến và dần xây dựng một mối quan hệ đời thực đầy lãng mạn.-",
    image: "/images/romantic/oo.jpg",
    videoUrl: "https://www.youtube.com/embed/NNP8m3gaaFE?si=NqM97PhP_HejZ18Y",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 71,
    title: "Thế giới hôn nhân",
    genre: "romance",
    releaseDate: "2021",
    description: "Phim kể về mối tình đầu khắc cốt ghi tâm giữa Hà Dĩ Thâm, một luật sư điển trai và Triệu Mặc Sênh, một cô gái ngây thơ. Sau nhiều năm xa cách vì hiểu lầm, họ gặp lại và đối mặt với quá khứ để tìm lại tình yêu.",
    image: "/images/romantic/moivie.jpg",
    videoUrl: "https://www.youtube.com/embed/-yEUwZfhLQg?si=YB2iAk7NJxMmzhVS",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 72,
    title: "chạm vào tim em",
    genre: "romance",
    releaseDate: "2020",
    description: "Han Thương Ngôn, một tuyển thủ game thể thao điện tử tài năng nhưng lạnh lùng, tình cờ gặp gỡ và bị cuốn vào sự đáng yêu của Đồng Niên, một nữ ca sĩ kiêm lập trình viên thông minh. Câu chuyện xoay quanh tình yêu, ước mơ, và sự nỗ lực trong cuộc sống.",
    image: "/images/romantic/moiviee.jpg",
    videoUrl: "https://www.youtube.com/embed/PPvYLZbUMk8?si=P02af85qr1jX5rtE",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 73,
    title: "Người tình ánh trăng",
    genre: "romance",
    releaseDate: "2023",
    description: "Tiểu Thất Sam Sam, một nhân viên văn phòng ngây thơ và đáng yêu, vô tình lọt vào mắt xanh của Phong Đằng, tổng tài lạnh lùng nhưng ấm áp. Tình yêu của họ dần nảy nở từ những tình huống dở khóc dở cười.",
    image: "/images/romantic/mmm.jpg",
    videoUrl: "https://www.youtube.com/embed/24DDYlpm7w0?si=Qytk6lj5ksy-26jh",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 74,
    title: "Cô nàng mạnh mẽ",
    genre: "romance",
    releaseDate: "2022",
    description: "Phim kể về chuyện tình dễ thương giữa Trần Tiểu Hy, cô gái tinh nghịch, và Giang Thần, chàng trai lạnh lùng nhưng tài giỏi. Tình yêu của họ bắt đầu từ thời cấp ba và kéo dài đến khi trưởng thành.",
    image: "/images/romantic/m.jpg",
    videoUrl: "https://www.youtube.com/embed/ytFg_4EdmNQ?si=Fdr9UUNeBiGLWM5F",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 75,
    title: "Khóa học yêu cấp tốc",
    genre: "romance",
    releaseDate: "2021",
    description: " Đường Tuyết, một cô gái mạnh mẽ, và Lê Ngữ Băng, một chàng trai tài năng trong bộ môn khúc côn cầu trên băng, từng là bạn thời thơ ấu. Họ gặp lại nhau và dần nhận ra tình cảm chân thành.",
    image: "/images/romantic/mm.jpg",
    videoUrl: "https://www.youtube.com/embed/jCtNJLW5MnI?si=hNe3kHNvEOJcN9mf",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 76,
    title: "Người nổi tiếng",
    genre: "romance",
    releaseDate: "2020",
    description: "Tiểu Thất Sam Sam, một nhân viên văn phòng ngây thơ và đáng yêu, vô tình lọt vào mắt xanh của Phong Đằng, tổng tài lạnh lùng nhưng ấm áp. Tình yêu của họ dần nảy nở từ những tình huống dở khóc dở cười.",
    image: "/images/romantic/mmmm.jpg",
    videoUrl: "https://www.youtube.com/embed/6ww0oAM8N6s?si=Nl5Pxq6dKWwnPs1h",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 77,
    title: "Hẹn gặp anh ở kiếp thứ 19",
    genre: "romance",
    releaseDate: "2023",
    description: "Phim lấy bối cảnh về thể thao điện tử, kể về Lục Lệ Thành, một tuyển thủ tài năng, và Khâu Anh, cô phóng viên nhiệt huyết. Tình yêu của họ được xây dựng từ sự đồng cảm và cùng nhau vượt qua thử thách.",
    image: "/images/romantic/v.jpg",
    videoUrl: "https://www.youtube.com/embed/YdIHWTqYse8?si=ThPUVhjn27aSLx40",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 78,
    title: "tình yêu và trói buộc",
    genre: "romance",
    releaseDate: "2022",
    description: "Chuyện tình nhiều sóng gió giữa Trình Tranh, một chàng trai giàu có, nhiệt huyết, và Tô Vận Cẩm, cô gái bình dị nhưng kiên cường. Tình yêu của họ trải qua nhiều lần tan hợp trước khi nhận ra ý nghĩa thật sự của hạnh phúc.",
    image: "/images/romantic/vv.jpg",
    videoUrl: "https://www.youtube.com/embed/2ULu_81QBUE?si=2FzZXkf4tLjrWdaA",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 79,
    title: "Hẹn hò chốn công sở",
    genre: "romance",
    releaseDate: "2021",
    description: "Chuyện tình nhiều sóng gió giữa Trình Tranh, một chàng trai giàu có, nhiệt huyết, và Tô Vận Cẩm, cô gái bình dị nhưng kiên cường. Tình yêu của họ trải qua nhiều lần tan hợp trước khi nhận ra ý nghĩa thật sự của hạnh phúc.",
    image: "/images/romantic/o.jpg",
    videoUrl: "https://www.youtube.com/embed/bR5Il90f1vE?si=HVoknfFkD97a6SVR",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 80,
    title: "Mù hè yêu dấu của chúng ta",
    genre: "romance",
    releaseDate: "2020",
    description: "Phim kể về chuyện tình dễ thương giữa Trần Tiểu Hy, cô gái tinh nghịch, và Giang Thần, chàng trai lạnh lùng nhưng tài giỏi. Tình yêu của họ bắt đầu từ thời cấp ba và kéo dài đến khi trưởng thành.",
    image: "/images/romantic/tt.jpg",
    videoUrl: "https://www.youtube.com/embed/lqU_kT4L0FQ?si=nnPH2XizNL08niax",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
];

const RomancePage = () => {
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    setMovies(moviesData.filter((movie) => movie.genre === "romance"));
  }, []);

  return (
    <div className="movie-list-page">
      <h1>Romance Movies</h1>
      <MovieList movies={movies} />
    </div>
  );
};

export default RomancePage;
