// src/pages/SciFiPage.js
import React, { useState, useEffect } from "react";
import MovieList from "../components/MovieList";

const moviesData = [
  {
    id: 21,
    title: "D N A",
    genre: "sci-fi",
    releaseDate: "2023",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/DAN.webp",
    videoUrl: "https://www.youtube.com/embed/yxOWJ6dGQDQ?si=Kvf37FjNcOO3pNvO",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 22,
    title: "Blood ",
    genre: "sci-fi",
    releaseDate: "2022",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/b8399661-5620-46c2-9986-a6e3e39aeb21.webp",
    videoUrl: "https://www.youtube.com/embed/ZVafEu7-4No?si=FqZ34QNZ0ADPpRSY",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 23,
    title: "Rise",
    genre: "sci-fi",
    releaseDate: "2021",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP.jpg",
    videoUrl: "https://www.youtube.com/embed/TPpO-zqqUH0?si=aHYdU_x1P-3OIRDg",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 24,
    title: "Inception",
    genre: "sci-fi",
    releaseDate: "2020",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/p22659982_v_v10_aa.jpg",
    videoUrl: "https://www.youtube.com/embed/fBFgg_OYcR4?si=81rEsZuB0AobD9Nd",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 25,
    title: "The Matrix",
    genre: "sci-fi",
    releaseDate: "2023",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (1).jpg",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 26,
    title: "Avatar",
    genre: "sci-fi",
    releaseDate: "2022",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/R.jpg",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 27,
    title: "Blade Runner 2049",
    genre: "sci-fi",
    releaseDate: "2021",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/R (1).jpg",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 28,
    title: "Star Wars: A New Hope",
    genre: "sci-fi",
    releaseDate: "2020",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (2).jpg",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 29,
    title: "Star Trek",
    genre: "sci-fi",
    releaseDate: "2023",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (3).jpg",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 30,
    title: "The Martian",
    genre: "sci-fi",
    releaseDate: "2022",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/1770002321-h.webp",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 31,
    title: "Gravity",
    genre: "sci-fi",
    releaseDate: "2021",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/R (2).jpg",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 32,
    title: "Arrival ",
    genre: "sci-fi",
    releaseDate: "2020",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (4).jpg",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 33,
    title: "Edge of Tomorrow",
    genre: "sci-fi",
    releaseDate: "2023",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (5).jpg",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 34,
    title: "Elysium",
    genre: "sci-fi",
    releaseDate: "2022",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (6).jpg",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 35,
    title: "Ex Machina",
    genre: "sci-fi",
    releaseDate: "2021",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (7).jpg",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 36,
    title: "Annihilation",
    genre: "sci-fi",
    releaseDate: "2020",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (8).jpg",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
  {
    id: 37,
    title: "Ready Player One",
    genre: "sci-fi",
    releaseDate: "2023",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (9).jpg",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub1.vtt",
    views: 500,
  },
  {
    id: 38,
    title: "District 9",
    genre: "sci-fi",
    releaseDate: "2022",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (10).jpg",
    videoUrl: "https://www.youtube.com/embed/VFNR-wFvOns?si=BH-FSfjf5TF_T92Q",
    subtitleUrl: "/subtitles/sub2.vtt",
    views: 750,
  },
  {
    id: 39,
    title: "Snowpiercer",
    genre: "sci-fi",
    releaseDate: "2021",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/OIP (11).jpg",
    videoUrl: "https://www.youtube.com/embed/5PvzGDU8WjM",
    subtitleUrl: "/subtitles/sub3.vtt",
    views: 1000,
  },
  {
    id: 40,
    title: "Pacific Rim",
    genre: "sci-fi",
    releaseDate: "2020",
    description: "sci-fi-packed adventure!",
    image: "/images/sci-fis/MV5BMTY3MTI5NjQ4Nl5BMl5BanBnXkFtZTcwOTU1OTU0OQ@@._V1_FMjpg_UX1000_.jpg",
    videoUrl: "https://www.youtube.com/embed/2nEgC35MoM4",
    subtitleUrl: "/subtitles/sub4.vtt",
    views: 1200,
  },
];

const SciFiPage = () => {
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    setMovies(moviesData.filter((movie) => movie.genre === "sci-fi"));
  }, []);

  return (
    <div className="movie-list-page">
      <h1>Sci-Fi Movies</h1>
      <MovieList movies={movies} />
    </div>
  );
};

export default SciFiPage;
